import { WeaponDefinition } from './types/index';

export const WEAPONS: WeaponDefinition[] = [
  {
    id: 'standard',
    name: 'Standard Shell',
    projectileSpeed: 24,
    blastRadius: 2.8,
    damage: 24,
    terrainDamage: 2.4,
    behavior: 'standard',
    cooldown: 0.9,
  },
  {
    id: 'big_blast',
    name: 'Big Blast',
    projectileSpeed: 16,
    blastRadius: 7,
    damage: 44,
    terrainDamage: 0,
    behavior: 'airburst',
    cooldown: 2.8,
    behaviorConfig: {
      airburstHeight: 2.8,
    },
  },
  {
    id: 'splitter',
    name: 'Splitter',
    projectileSpeed: 21,
    blastRadius: 2,
    damage: 12,
    terrainDamage: 1.2,
    behavior: 'split',
    cooldown: 1.6,
    behaviorConfig: {
      splitTime: 0.7,
      fragmentCount: 3,
      fragmentSpread: 0.34,
      fragmentSpeedScale: 0.9,
      fragmentBlastRadius: 2.2,
      fragmentDamage: 14,
      fragmentTerrainDamage: 1.5,
    },
  },
  {
    id: 'bouncer',
    name: 'Bouncer',
    projectileSpeed: 22,
    blastRadius: 3.2,
    damage: 22,
    terrainDamage: 2,
    behavior: 'bounce',
    cooldown: 1.8,
    behaviorConfig: {
      bounceCount: 1,
      bounceDamping: 0.72,
    },
  },
  {
    id: 'drill',
    name: 'Drill',
    projectileSpeed: 20,
    blastRadius: 2.4,
    damage: 10,
    terrainDamage: 0,
    behavior: 'drill',
    cooldown: 2.2,
    behaviorConfig: {
      drillDelay: 0.45,
      drillDistance: 5.5,
      drillBlastRadius: 3.6,
      drillDamage: 34,
      drillTerrainDamage: 4.5,
    },
  },
  {
    id: 'napalm',
    name: 'Napalm',
    projectileSpeed: 18,
    blastRadius: 2.2,
    damage: 10,
    terrainDamage: 0.4,
    behavior: 'napalm',
    cooldown: 2.6,
    behaviorConfig: {
      burnRadius: 4.4,
      burnDuration: 5.5,
      burnTickDamage: 7,
      burnTickInterval: 0.55,
    },
  },
  {
    id: 'seeker',
    name: 'Seeker',
    projectileSpeed: 13,
    blastRadius: 3,
    damage: 30,
    terrainDamage: 0.8,
    behavior: 'seeker',
    cooldown: 3.2,
    behaviorConfig: {
      seekerTurnRate: 3.8,
      seekerLifetime: 5.2,
      seekerTargetRadius: 24,
    },
  },
  {
    id: 'rail',
    name: 'Rail',
    projectileSpeed: 60,
    blastRadius: 1.4,
    damage: 42,
    terrainDamage: 0.2,
    behavior: 'rail',
    cooldown: 2.7,
    behaviorConfig: {
      railRange: 50,
      railRadius: 1.4,
      railTerrainDamage: 0.2,
    },
  },
  {
    id: 'mortar_rain',
    name: 'Mortar Rain',
    projectileSpeed: 14,
    blastRadius: 3.6,
    damage: 18,
    terrainDamage: 2.4,
    behavior: 'mortar',
    cooldown: 2.8,
    behaviorConfig: {
      mortarShellCount: 5,
      mortarSpread: 5.5,
      mortarInterval: 0.28,
      mortarSpawnHeight: 20,
      mortarImpactRadius: 3.4,
      mortarImpactDamage: 20,
      mortarTerrainDamage: 2.5,
    },
  },
  {
    id: 'dig',
    name: 'Digger',
    projectileSpeed: 22,
    blastRadius: 0.8,
    damage: 0,
    terrainDamage: 0,
    behavior: 'dig',
    cooldown: 1.2,
    behaviorConfig: {
      digLength: 6,
      digStartRadius: 1.0,
      digEndRadius: 2.4,
      digDepth: 4.5,
    },
  },
  {
    id: 'mine',
    name: 'Mine Layer',
    projectileSpeed: 14,
    blastRadius: 3.2,
    damage: 12,
    terrainDamage: 0,
    behavior: 'mine',
    cooldown: 2.4,
    behaviorConfig: {
      mineArmTime: 0.8,
      mineLifetime: 14,
      mineTriggerRadius: 2.5,
      mineBlastRadius: 3.6,
      mineDamage: 36,
      mineTerrainDamage: 2.8,
    },
  },
];
